receivers:
  otlp:
    protocols:
      http:
        endpoint: otel-collector:4318
      grpc:
        endpoint: otel-collector:4317

processors:
  # batch metrics before sending to reduce API usage
  batch:
# https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/README.md
extensions:
  # responsible for responding to health check calls on behalf of the collector.
  health_check:
    endpoint: otel-collector:13133
  # fetches the collector’s performance data
  pprof:
    endpoint: otel-collector:1888
  # serves as an http endpoint that provides live debugging data about instrumented components.
  zpages:
    endpoint: otel-collector:55679
exporters:
  jaeger:
    sampler:
      type: const
      param: 1
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true
service:
  extensions:
    - health_check
    - pprof
    - zpages
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - jaeger