server:
  servlet:
    context-path: /customer-service
spring:
  application:
    name: customer-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_HOST}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - info
          - health
          - metrics
          - prometheus
info:
  app:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@
    build:
      artifact: @project.artifactId@
      group: @project.groupId@
      version: @project.version@