global:
  # How frequently to scrape targets by default.
  scrape_interval: 15s

scrape_configs:
  - job_name: 'customer-service'
    metrics_path: '/customer-service/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']